[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "m2r_stochastic_resetting"
version = "0.1"
dependencies = ["numpy"]

[tool.hatch.build.targets.wheel]
packages = ["stochastic_resetting"]